<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006120001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'DBAL 4: drop the DC2Type column comments, turn the serial ids into identity columns';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE IF EXISTS messenger_messages_id_seq');
        $this->addSql('ALTER TABLE messenger_messages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('SELECT setval(pg_get_serial_sequence(\'messenger_messages\', \'id\'), COALESCE((SELECT MAX(id) FROM messenger_messages), 0) + 1, false)');

        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS NULL');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_notification.id IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_notification.subscriber_id IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_notification.read_at IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_notification.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_preference.id IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_preference.subscriber_id IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_preference.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_digest.id IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_digest.subscriber_id IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_digest.first_event_at IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_digest.last_event_at IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_digest.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_subscriber.id IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_subscriber.user_id IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_subscriber.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_subscriber.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_broadcast.id IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_broadcast.initiator_user_id IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_broadcast.exclude_user_id IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_broadcast.started_at IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_broadcast.completed_at IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_broadcast.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_subscription.id IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_subscription.subscriber_id IS NULL');
        $this->addSql('COMMENT ON COLUMN notifier_subscription.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN publication_profile.id IS NULL');
        $this->addSql('COMMENT ON COLUMN publication_profile.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN publication_profile.config_begins_at IS NULL');
        $this->addSql('COMMENT ON COLUMN publication_profile.config_expires_at IS NULL');
        $this->addSql('COMMENT ON COLUMN asset.id IS NULL');
        $this->addSql('COMMENT ON COLUMN asset.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN asset.publication_id IS NULL');
        $this->addSql('COMMENT ON COLUMN env_var.id IS NULL');
        $this->addSql('COMMENT ON COLUMN env_var.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN env_var.updated_at IS NULL');
        $this->addSql('COMMENT ON COLUMN publication.id IS NULL');
        $this->addSql('COMMENT ON COLUMN publication.package_id IS NULL');
        $this->addSql('COMMENT ON COLUMN publication.parent_id IS NULL');
        $this->addSql('COMMENT ON COLUMN publication.config_begins_at IS NULL');
        $this->addSql('COMMENT ON COLUMN publication.config_expires_at IS NULL');
        $this->addSql('COMMENT ON COLUMN publication.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN publication.profile_id IS NULL');
        $this->addSql('COMMENT ON COLUMN publication.cover_id IS NULL');
        $this->addSql('COMMENT ON COLUMN publication.date IS NULL');
        $this->addSql('COMMENT ON COLUMN download_request.id IS NULL');
        $this->addSql('COMMENT ON COLUMN download_request.publication_id IS NULL');
        $this->addSql('COMMENT ON COLUMN download_request.asset_id IS NULL');
        $this->addSql('COMMENT ON COLUMN download_request.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN download_request.sub_definition_id IS NULL');
        $this->addSql('COMMENT ON COLUMN sub_definition.id IS NULL');
        $this->addSql('COMMENT ON COLUMN sub_definition.asset_id IS NULL');
        $this->addSql('COMMENT ON COLUMN sub_definition.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN multipart_upload.id IS NULL');
        $this->addSql('COMMENT ON COLUMN multipart_upload.created_at IS NULL');
        $this->addSql('COMMENT ON COLUMN access_control_entry.id IS NULL');
        $this->addSql('COMMENT ON COLUMN access_control_entry.object_id IS NULL');
        $this->addSql('COMMENT ON COLUMN access_control_entry.created_at IS NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifier_notification.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notifier_notification.subscriber_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notifier_notification.read_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifier_notification.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifier_preference.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notifier_preference.subscriber_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notifier_preference.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifier_digest.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notifier_digest.subscriber_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notifier_digest.first_event_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifier_digest.last_event_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifier_digest.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifier_subscriber.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notifier_subscriber.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notifier_subscriber.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifier_subscriber.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifier_broadcast.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notifier_broadcast.initiator_user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notifier_broadcast.exclude_user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notifier_broadcast.started_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifier_broadcast.completed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifier_broadcast.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN notifier_subscription.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notifier_subscription.subscriber_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notifier_subscription.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN publication_profile.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN publication_profile.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN publication_profile.config_begins_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN publication_profile.config_expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN asset.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN asset.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN asset.publication_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN env_var.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN env_var.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN env_var.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN publication.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN publication.package_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN publication.parent_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN publication.config_begins_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN publication.config_expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN publication.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN publication.profile_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN publication.cover_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN publication.date IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN download_request.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN download_request.publication_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN download_request.asset_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN download_request.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN download_request.sub_definition_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN sub_definition.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN sub_definition.asset_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN sub_definition.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN multipart_upload.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN multipart_upload.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN access_control_entry.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN access_control_entry.object_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN access_control_entry.created_at IS \'(DC2Type:datetime_immutable)\'');

        $this->addSql('ALTER TABLE messenger_messages ALTER id DROP IDENTITY');
        $this->addSql('CREATE SEQUENCE messenger_messages_id_seq OWNED BY messenger_messages.id');
        $this->addSql('SELECT setval(\'messenger_messages_id_seq\', COALESCE((SELECT MAX(id) FROM messenger_messages), 0) + 1, false)');
        $this->addSql('ALTER TABLE messenger_messages ALTER id SET DEFAULT nextval(\'messenger_messages_id_seq\')');
    }
}
