alchemy_acl:
  objects:
    !php/const:App\Entity\AttributeList\AttributeList::OBJECT_TYPE: App\Entity\AttributeList\AttributeList
    !php/const:App\Entity\Basket\Basket::OBJECT_TYPE: App\Entity\Basket\Basket
    !php/const:App\Entity\Core\Asset::OBJECT_TYPE: App\Entity\Core\Asset
    !php/const:App\Entity\Core\AttributePolicy::OBJECT_TYPE: App\Entity\Core\AttributePolicy
    !php/const:App\Entity\Core\Collection::OBJECT_TYPE: App\Entity\Core\Collection
    !php/const:App\Entity\Core\RenditionPolicy::OBJECT_TYPE: App\Entity\Core\RenditionPolicy
    !php/const:App\Entity\Core\Workspace::OBJECT_TYPE: App\Entity\Core\Workspace
    !php/const:App\Entity\Integration\WorkspaceIntegration::OBJECT_TYPE: App\Entity\Integration\WorkspaceIntegration
    !php/const:App\Entity\SavedSearch\SavedSearch::OBJECT_TYPE: App\Entity\SavedSearch\SavedSearch
    !php/const:App\Entity\Template\AssetDataTemplate::OBJECT_TYPE: App\Entity\Template\AssetDataTemplate
    !php/const:App\Entity\Page\Page::OBJECT_TYPE: App\Entity\Page\Page
  enabled_permissions:
    - VIEW
    - CREATE
    - EDIT
    - DELETE
    - OPERATOR
    - MASTER
    - OWNER
    - SHARE
    - CHILD_VIEW
    - CHILD_CREATE
    - CHILD_EDIT
    - CHILD_DELETE
    - CHILD_UNDELETE
    - CHILD_OPERATOR
    - CHILD_MASTER
    - CHILD_OWNER
    - CHILD_SHARE
