parameters:
    env(DATABOX_IMPERSONATION_ENABLED): false

alchemy_auth:
    impersonation:
        enabled: '%env(bool:DATABOX_IMPERSONATION_ENABLED)%'

when@test:
    alchemy_auth:
        impersonation:
            enabled: true
