<?php

declare(strict_types=1);

namespace Alchemy\ESBundle\Controller\Admin;

use Alchemy\ESBundle\Admin\ESIndexAdmin;
use EasyCorp\Bundle\EasyAdminBundle\Attribute\AdminRoute;
use Elastic\Elasticsearch\Exception\ElasticsearchException;
use Elastic\Transport\Exception\TransportException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * EasyAdmin screens to inspect and manage the Elasticsearch indices and aliases.
 *
 * Routes are generated by EasyAdmin under the dashboard prefix, e.g.
 * /admin/elasticsearch (route "easyadmin_es_index" for the "easyadmin" dashboard).
 */
#[AdminRoute('/elasticsearch', name: 'es')]
final class ESIndexAdminController extends AbstractController
{
    public const string CSRF_TOKEN_ID = 'alchemy_es_admin';

    public const string ROUTE_INDEX = 'index';
    public const string ROUTE_INDEX_DETAIL = 'index_detail';
    public const string ROUTE_INDEX_DELETE = 'index_delete';
    public const string ROUTE_INDEX_OPEN = 'index_open';
    public const string ROUTE_INDEX_CLOSE = 'index_close';
    public const string ROUTE_INDEX_REFRESH = 'index_refresh';
    public const string ROUTE_LOGICAL_RESET = 'logical_reset';
    public const string ROUTE_LOGICAL_CLEAN_OLDS = 'logical_clean_olds';
    public const string ROUTE_ALIAS_ADD = 'alias_add';
    public const string ROUTE_ALIAS_REMOVE = 'alias_remove';
    public const string ROUTE_ALIAS_SWITCH = 'alias_switch';

    private const array POST = ['methods' => ['POST']];

    public function __construct(
        private readonly ESIndexAdmin $admin,
    ) {
    }

    /**
     * Full Symfony route name of one of the ROUTE_* constants.
     */
    public static function routeName(string $route, string $dashboardRouteName = 'easyadmin'): string
    {
        return \sprintf('%s_es_%s', $dashboardRouteName, $route);
    }

    #[AdminRoute('/', name: self::ROUTE_INDEX)]
    public function index(): Response
    {
        return $this->render('@AlchemyES/admin/index.html.twig', [
            'logicalIndices' => $this->admin->getLogicalIndices(),
            'physicalIndices' => $this->admin->getPhysicalIndices(),
            'aliases' => $this->admin->getAliases(),
            'roles' => [
                ESIndexAdmin::ROLE_ACTIVE => 'success',
                ESIndexAdmin::ROLE_DIRECT => 'success',
                ESIndexAdmin::ROLE_OLD => 'warning',
                ESIndexAdmin::ROLE_SYSTEM => 'secondary',
                ESIndexAdmin::ROLE_UNMANAGED => 'info',
            ],
        ]);
    }

    #[AdminRoute('/index/{name}', name: self::ROUTE_INDEX_DETAIL)]
    public function detail(string $name): Response
    {
        if (!$this->admin->indexExists($name)) {
            $this->addFlash('danger', \sprintf('Index "%s" does not exist.', $name));

            return $this->redirectToIndex();
        }

        $details = $this->admin->getIndexDetails($name);

        return $this->render('@AlchemyES/admin/detail.html.twig', [
            'name' => $name,
            'isLogicalIndex' => $this->admin->isLogicalIndex($name),
            'details' => $details,
            'json' => [
                'settings' => self::prettyJson($details['settings']),
                'mappings' => self::prettyJson($details['mappings']),
                'stats' => self::prettyJson($details['stats']),
            ],
        ]);
    }

    #[AdminRoute('/index/{name}/delete', name: self::ROUTE_INDEX_DELETE, options: self::POST)]
    public function delete(Request $request, string $name): Response
    {
        return $this->mutate($request, function () use ($name): string {
            $this->admin->deleteIndex($name);

            return \sprintf('Index "%s" has been deleted.', $name);
        });
    }

    #[AdminRoute('/index/{name}/open', name: self::ROUTE_INDEX_OPEN, options: self::POST)]
    public function open(Request $request, string $name): Response
    {
        return $this->mutate($request, function () use ($name): string {
            $this->admin->openIndex($name);

            return \sprintf('Index "%s" has been opened.', $name);
        });
    }

    #[AdminRoute('/index/{name}/close', name: self::ROUTE_INDEX_CLOSE, options: self::POST)]
    public function close(Request $request, string $name): Response
    {
        return $this->mutate($request, function () use ($name): string {
            $this->admin->closeIndex($name);

            return \sprintf('Index "%s" has been closed.', $name);
        });
    }

    #[AdminRoute('/index/{name}/refresh', name: self::ROUTE_INDEX_REFRESH, options: self::POST)]
    public function refresh(Request $request, string $name): Response
    {
        return $this->mutate($request, function () use ($name): string {
            $this->admin->refreshIndex($name);

            return \sprintf('Index "%s" has been refreshed.', $name);
        });
    }

    #[AdminRoute('/logical/{name}/reset', name: self::ROUTE_LOGICAL_RESET, options: self::POST)]
    public function resetLogical(Request $request, string $name): Response
    {
        return $this->mutate($request, function () use ($name): string {
            $this->admin->resetLogicalIndex($name);

            return \sprintf('Index "%s" has been recreated (empty, with the configured mapping). Run a populate to fill it.', $name);
        });
    }

    #[AdminRoute('/logical/{name}/clean-olds', name: self::ROUTE_LOGICAL_CLEAN_OLDS, options: self::POST)]
    public function cleanOlds(Request $request, string $name): Response
    {
        return $this->mutate($request, function () use ($name): string {
            $removed = $this->admin->removeOldIndices($name);

            return [] === $removed
                ? \sprintf('No old index to remove for "%s".', $name)
                : \sprintf('Removed %d old index(es) of "%s": %s', \count($removed), $name, implode(', ', $removed));
        });
    }

    #[AdminRoute('/alias/add', name: self::ROUTE_ALIAS_ADD, options: self::POST)]
    public function addAlias(Request $request): Response
    {
        return $this->mutate($request, function () use ($request): string {
            [$index, $alias] = $this->getAliasParams($request);
            $this->admin->addAlias($index, $alias);

            return \sprintf('Alias "%s" now points to index "%s".', $alias, $index);
        });
    }

    #[AdminRoute('/alias/remove', name: self::ROUTE_ALIAS_REMOVE, options: self::POST)]
    public function removeAlias(Request $request): Response
    {
        return $this->mutate($request, function () use ($request): string {
            [$index, $alias] = $this->getAliasParams($request);
            $this->admin->removeAlias($index, $alias);

            return \sprintf('Alias "%s" has been removed from index "%s".', $alias, $index);
        });
    }

    #[AdminRoute('/alias/switch', name: self::ROUTE_ALIAS_SWITCH, options: self::POST)]
    public function switchAlias(Request $request): Response
    {
        return $this->mutate($request, function () use ($request): string {
            [$index, $alias] = $this->getAliasParams($request);
            $previous = $this->admin->switchAlias($alias, $index);

            return [] === $previous
                ? \sprintf('Alias "%s" now points to index "%s".', $alias, $index)
                : \sprintf('Alias "%s" switched to index "%s" (removed from: %s).', $alias, $index, implode(', ', $previous));
        });
    }

    /**
     * @return array{0: string, 1: string} [index, alias]
     */
    private function getAliasParams(Request $request): array
    {
        $index = trim((string) $request->request->get('index', ''));
        $alias = trim((string) $request->request->get('alias', ''));

        if ('' === $index || '' === $alias) {
            throw new \InvalidArgumentException('Both "index" and "alias" are required.');
        }
        if ($index === $alias) {
            throw new \InvalidArgumentException('An alias cannot have the same name as its index.');
        }

        return [$index, $alias];
    }

    /**
     * @param callable(): string $action returns the success message
     */
    private function mutate(Request $request, callable $action): Response
    {
        if (!$this->isCsrfTokenValid(self::CSRF_TOKEN_ID, (string) $request->request->get('token'))) {
            $this->addFlash('danger', 'Invalid CSRF token, nothing was done. Please retry.');

            return $this->redirectToIndex();
        }

        try {
            $this->addFlash('success', $action());
        } catch (ElasticsearchException|TransportException|\InvalidArgumentException|\RuntimeException $e) {
            $this->addFlash('danger', \sprintf('Elasticsearch error: %s', $e->getMessage()));
        }

        return $this->redirectToIndex();
    }

    private function redirectToIndex(): Response
    {
        return $this->redirectToRoute(self::routeName(self::ROUTE_INDEX, $this->getDashboardRouteName()));
    }

    /**
     * Route name of the dashboard whose route is being served (e.g. "easyadmin"),
     * so that redirections stay on the current dashboard.
     */
    private function getDashboardRouteName(): string
    {
        $route = (string) $this->container->get('request_stack')->getCurrentRequest()?->attributes->get('_route');

        return preg_replace('/_es_[a-z_]+$/', '', $route) ?: 'easyadmin';
    }

    private static function prettyJson(array $data): string
    {
        return json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) ?: '{}';
    }
}
