imports:
    - './services_dev.yaml'

services:
    App\Tests\Functional\Rendition\Phraseanet\PhraseanetApiClientFactoryMock: ~
    App\Integration\Phraseanet\PhraseanetApiClientFactory: '@App\Tests\Functional\Rendition\Phraseanet\PhraseanetApiClientFactoryMock'
