alchemy_notifier:
    enabled: '%env(bool:NOTIFICATIONS_ENABLED)%'
    template_namespace: '@notifications'
    default_channels: [email]
    topics:
        # Transactional emails sent to anonymous download requesters
        'download:link':
            channels: [email]
        'download:zippy_link':
            channels: [email]

twig:
    paths:
        '%kernel.project_dir%/templates/notifications': notifications
